# This workflow will run all checks required for a PR to be merged.

name: pr
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: print token
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
          NOT_A_SECRET: hello this is not a secret
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        with:
          script: |
            console.log(process.env.NOT_A_SECRET)

