# This workflow will run all checks required for a PR to be merged.

name: pr
on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Download build artifact
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        env:
          MY_SECRET: ${{ secrets.CANARY_DEPLOY_TOKEN }}
        run: echo $CANARY_DEPLOY_TOKEN

